spring:
  application:
    name: notification-service
  cloud:
    stream:
      source: notificationEventSupplier
      bindings:
        notificationEventSupplier-in-0:
          destination: notification-events
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/