spring:
  application:
    name: order-service
  config:
    import:
      - configserver:http://localhost:8888
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8081