spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/microservice
        registration:
          spring-cloud-gateway-client:
            client-id: spring-cloud-gateway-client
            client-secret: b15d3b25-7194-41a0-961a-ca8adf4e7fa2
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/spring-cloud-gateway-client
server:
  port: 9090
